### PR TITLE
Add client side validation

### PR DESCRIPTION
**Pull request by abdallahmalima**
**Note:**'I have been made solo late in the week with approval from Student Success. Please reach out to Marco Lizza in the Student Success team if you need to verify it.'

### In this part I:

- Add validation for the email field to submit only if the email is lowercase

### CODE REVIEW

**Review by Bondok6 — COMMENTED** [review]
## Hi @abdallahmalima 🙋‍♂️, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has been done individually and this is a pair programming project. Everyone on your team should make a commit in this PR.

image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by abdallahmalima** [comment]
Hi @Bondok6  today microverse  unpaired me with my partner because he had some personal issue

**Comment by Bondok6** [comment]
Hi @abdallahmalima, 

Please, can you provide a screenshot of a message you have received from the student success in this regard?

**Comment by abdallahmalima** [comment]
Hello @Bondok6  kindly find the screenshot of lizza's email from microverse

image

**Comment by Bondok6** [comment]
Hey @abdallahmalima,
You can re-submit this PR (request a review), and another reviewer will review your project 👍

**Review by HAMMAS-SALEEM — APPROVED** [review]
# Status: Approved :green_circle: :1st_place_medal: :100:
success

## Hey @abdallahmalima :wave:

Great work on implementing the requirements. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

:heavy_check_mark: Following Requirements
:heavy_check_mark: Following Github Flow
:heavy_check_mark: Descriptive PR Title
:heavy_check_mark: Descriptive PR Summary
:heavy_check_mark: Following Linters

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
